---
# File: deploy_application.yml

- name: Application Deployment Playbook
  hosts: app_servers
  become: yes
  vars:
    app_name: "my_application"
    repo_url: "https://github.com/your_org/your_repo.git"
    app_dir: "/var/www/my_application"
    branch: "main"
    service_name: "my_application_service"

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.yum:
        name: 
          - git
          - python3
        state: present

    - name: Clone or update the application repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: Install application dependencies
      ansible.builtin.shell:
        cmd: |
          pip3 install -r requirements.txt
        chdir: "{{ app_dir }}"
      register: pip_install
      failed_when: pip_install.rc != 0

    - name: Set correct permissions
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        recurse: yes
        owner: www-data
        group: www-data

    - name: Restart the application service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: true
